# Generated by security hardening task on 2026-06-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bind", "0003_alter_bindinfo_unique_together_bindinfo_logged_in_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bindinfo",
            unique_together={("user", "device_id"), ("user", "ip")},
        ),
    ]
